# Generated by Django 6.0.4 on 2026-04-25 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('daily_saving_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('daily_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gap', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='savings.savingsgoal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
